### ISSUE TITLE
where the database file ?

### ISSUE THREAD

**Issue by nabilchen96** [dikiwidia/simpeg#1]
where the database file ?

**Comment by dikiwidia** [comment]
> 
> 
> where the database file ?

Sorry, I was forgot ... I'll be send for you by email ASAP

**Comment by masdianto** [comment]
bang izin data base nya belom tertera email saya masdianto.purba@gmail.com

**Comment by dikiwidia** [comment]
> bang izin data base nya belom tertera email saya [masdianto.purba@gmail.com](mailto:masdianto.purba@gmail.com)

Maaf ini sebelumnya, saya lupa simpan databasenya. Sudah lama tidak mengembangkan ini juga, maaf banget mas dan terimakasih sudah berkunjung ke kemari
